---
name: torrust
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./storage/proxy/webroot:/var/www/html
      - ./storage/certbot/etc:/etc/letsencrypt
      - ./storage/certbot/lib:/var/lib/letsencrypt
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - proxy
    network_mode: host

  proxy:
    image: nginx:mainline-alpine
    container_name: proxy
    restart: unless-stopped
    volumes:
      - ./storage/proxy/webroot:/var/www/html
      - ./storage/proxy/etc/nginx-conf:/etc/nginx/conf.d
      - ./storage/certbot/etc:/etc/letsencrypt
      - ./storage/certbot/lib:/var/lib/letsencrypt
      - ./storage/dhparam:/etc/ssl/certs
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - index-gui
      - index
      - tracker
      - grafana
    network_mode: host

  index-gui:
    image: torrust/index-gui:develop
    container_name: index-gui
    tty: true
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID}
      - NUXT_PUBLIC_API_BASE=${TORRUST_INDEX_GUI_API_BASE_URL:-http://localhost:3001/v1}
      - NITRO_HOST=${NITRO_HOST:-127.0.0.1}
      - NITRO_PORT=${NITRO_PORT:-3000}
    volumes:
      - ./storage/index-gui/log:/var/log/torrust/index-gui:Z
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - index
      - tracker
    network_mode: host

  index:
    image: torrust/index:develop
    container_name: index
    tty: true
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID}
      - TORRUST_INDEX_DATABASE=${TORRUST_INDEX_DATABASE:-sqlite3}
      - TORRUST_INDEX_DATABASE_DRIVER=${TORRUST_INDEX_DATABASE_DRIVER:-sqlite3}
      - TORRUST_INDEX_CONFIG_OVERRIDE_TRACKER__TOKEN=${TORRUST_INDEX_CONFIG_OVERRIDE_TRACKER__TOKEN:-MyAccessToken}
      - TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__USER_CLAIM_TOKEN_PEPPER=${TORRUST_INDEX_CONFIG_OVERRIDE_AUTH__USER_CLAIM_TOKEN_PEPPER:-MaxVerstappenWC2021}
      - TORRUST_INDEX_API_CORS_PERMISSIVE=${TORRUST_INDEX_API_CORS_PERMISSIVE:-true}
    volumes:
      - ./storage/index/lib:/var/lib/torrust/index:Z
      - ./storage/index/log:/var/log/torrust/index:Z
      - ./storage/index/etc:/etc/torrust/index:Z
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - tracker
    network_mode: host

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_SERVER_HTTP_PORT=3100
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    network_mode: host

  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    tty: true
    restart: unless-stopped
    volumes:
      - ./storage/prometheus/etc:/etc/prometheus:Z
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - tracker
    network_mode: host

  tracker:
    image: torrust/tracker:develop
    container_name: tracker
    tty: true
    restart: unless-stopped
    environment:
      - USER_ID=${USER_ID}
      - TORRUST_TRACKER_DATABASE=${TORRUST_TRACKER_DATABASE:-sqlite3}
      - TORRUST_TRACKER_CONFIG_OVERRIDE_CORE__DATABASE__DRIVER=${TORRUST_TRACKER_CONFIG_OVERRIDE_CORE__DATABASE__DRIVER:-sqlite3}
      - TORRUST_TRACKER_CONFIG_OVERRIDE_HTTP_API__ACCESS_TOKENS__ADMIN=${TORRUST_TRACKER_CONFIG_OVERRIDE_HTTP_API__ACCESS_TOKENS__ADMIN:-MyAccessToken}
    volumes:
      - ./storage/tracker/lib:/var/lib/torrust/tracker:Z
      - ./storage/tracker/log:/var/log/torrust/tracker:Z
      - ./storage/tracker/etc:/etc/torrust/tracker:Z
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    network_mode: host

volumes:
  mysql_data: {}
  grafana_data: {}
